### ISSUE TITLE
I Can Run It Without This Popping Up Image Linked?

### ISSUE THREAD

**Issue by isaac123467** [Disembleergon/NL2_Control-Panel#1]
![image](https://user-images.githubusercontent.com/89317987/233780141-a1a9d318-f845-4cc4-ade7-5644a25ab102.png)

**Comment by Disembleergon** [comment]
Seems like you didn't run install.bat at first. This should fix the issue.

If not, check if you installed all the prerequisites:
Python
NodeJS
MS Build Tools

You can find all the links to those programs in the README
