### ISSUE TITLE
I Have Got This Popping Up?

### ISSUE THREAD

**Issue by isaac123467** [Disembleergon/NL2_Control-Panel#2]
I Have Installed All The Programs Needed For This But: 
![image](https://github.com/Disembleergon/NL2_Control-Panel/assets/89317987/b00884e4-d82b-40f6-9f51-95cb1ee1d32b)

**Comment by Disembleergon** [comment]
Well, that's weird.
Could you please run install.bat in a terminal and show me the output?
There has to be a problem while installing, maybe something's missing.

**Comment by isaac123467** [comment]
https://github.com/Disembleergon/NL2_Control-Panel/assets/89317987/9d467000-07dd-4c3b-976c-82751960799e

**Comment by Disembleergon** [comment]
Seems like you didn't install Python. If you did, you probably didn't check the "add to Path" checkbox while installing. 

Best option is to uninstall Python and reinstall it with the checkbox activated. Just comment please when it worked

**Comment by isaac123467** [comment]
Ok

**Comment by Disembleergon** [comment]
After investigating I finally found out. As you can see in the README, you don't have to install python and MS Build Tools anymore, just install NodeJS LTS with the checkmark activated (in the installer).

**Comment by Disembleergon** [comment]
Gonna close the issue now. If you have questions or feedback, you can always contact me 😄
